### PR TITLE
Reorganize project layout

### PR DESCRIPTION
**Pull request by ishkawa**
We should support Swift 3 as soon as possible, but we encounter trouble in running CI jobs.
To resolve this, I have made following changes:

- Introduce Action.xcworkspace to build dependencies using git submodule.
  - Submodules are checked out by `carthage update --use-submodules`.
  - No tool update is required to follow Xcode update.
  - This layout is the same as that of ReactiveCocoa repository.
- Merge Demo.xcodeproj into Action.xcodeproj.
- Run CI jobs on Xcode 8.

### CODE REVIEW

**Comment by ishkawa** [comment]
@ashfurrow Thank you for reviewing this PR ✨ 

Could you release current master as 1.3.0? It may be the last version which supports Swift 2.x, and there're some merged PRs which is not contained in version releases.

**Comment by ishkawa** [comment]
I noticed RxSwiftCommunity does not have write access to this repository, is it intended? Some other repositories give write access to the organization, and I think it is better to keep repository active.

**Comment by ashfurrow** [comment]
Ah, no that's unintentional. Should be fixed now.

**Comment by ashfurrow** [comment]
Ok, cool. I'll release 95be402a90189566aaab036cf32f717c8eed17b3 (master as of this merge) later this afternoon.

**Comment by ishkawa** [comment]
Great 👍 Thank you!

**Comment by ashfurrow** [comment]
1.3.0 is released, is there any reason to wait before releasing a version for Swift 3?

**Comment by ishkawa** [comment]
Since the latest released of RxSwift for Swift 3 is still beta, I think our release for Swift 3 (possibly 2.0?) should also be beta.

**Comment by ashfurrow** [comment]
Makes sense. So I should release a `2.0.0-beta.1` you think?

**Comment by ishkawa** [comment]
Yes 👍

**Comment by ashfurrow** [comment]
Okay, pushed as 2.0.0-beta.1, let me know if you run into any issues, and thanks again!

**Pull request merged**
