### PR TITLE
Update RxSwift to 3.3.1

### PR DESCRIPTION
**Pull request by yuzushioh**

### CODE REVIEW

**Comment by freak4pc** [comment]
There's no reason so have such strict versioning. 

Changing to `~> 3.0` should be open enough and still allow more modern RxSwift users to use Action. Some other people are using older RxSwift versions and don't necessarily want to upgrade.

**Comment by yuzushioh** [comment]
@freak4pc Thank you for the comment! 

I thought that changing it to RxSwift 3.3.0 should be open enough as well but then I found this [#1134](https://github.com/ReactiveX/RxSwift/issues/1134) that `Completable` was misspelled. so I though that it would be better to change it to RxSwift3.3.1 instead. But just changing to `~3.3.0` would work too👍

**Comment by freak4pc** [comment]
Not 3.3.0, just ~3.0 :) That would allow old users as well to use Action.

**Comment by yuzushioh** [comment]
I will fix this now👍

**Pull request closed without merging**
