### PR TITLE
[Testing] Testing Peril integration

### PR DESCRIPTION
**Pull request by ashfurrow**
Please ignore! See conversation in https://github.com/RxSwiftCommunity/contributors/pull/35 for details.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Hmm, this should have caused a Peril warning. Will investigate.

**Comment by freak4pc** [comment]
@ashfurrow Peril should've failed here, right?

**Comment by ashfurrow** [comment]
Yes exactly – it should have failed. I've verified in Heroku's logs that Peril _is_ getting invoked, so I [added some debugging statements](https://github.com/RxSwiftCommunity/peril/commit/86ede54bfdcde047d3a48a3a7d3acc27b1f4c600) to see what's going on.

**Comment by freak4pc** [comment]
console.log is the only proper debugging method 😂🤓

**Comment by ashfurrow** [comment]
Truly it is!

This is very odd – the logs indicate that we _are_ calling the `warn` function:

```
2018-01-01T22:13:05.437171+00:00 heroku[router]: at=info method=POST path="/webhook" host=peril-rxswiftcommunity.herokuapp.com request_id=410f4788-74ff-4504-a38f-a9eb380ed5c0 fwd="192.30.252.40" dyno=web.1 connect=1ms service=1131ms status=200 bytes=352 protocol=https
2018-01-01T22:13:05.595135+00:00 app[web.1]: hasChangelog:  /* A JS object */ markedTrivial:  false
2018-01-01T22:13:05.595664+00:00 app[web.1]: hasCodeChanges:  Sources/Action/Action.swift hasChangelogChanges:  undefined
2018-01-01T22:13:05.595776+00:00 app[web.1]: We're going to markdown or warn function (message) { return results.markdowns.push(message); } function (message) { return results.warnings.push({ message: message }); }
2018-01-01T22:13:05.694054+00:00 app[web.1]: No issues or messages were sent. Removing any existing messages.
```

Peril is indicating that no issues or messages were sent. This is probably a configuration error or something silly – I'll keep investigating. @orta any obvious things I may have overlooked?

**Comment by ashfurrow** [comment]
Okay, so [these lines](https://github.com/danger/danger-js/blob/7995114415e860455ea814993e1a6e7eb6dccf6d/source/runner/Executor.ts#L164-L180) are getting executed. I [added more logging](https://github.com/RxSwiftCommunity/peril/commit/e09b3c48c743fe8c78d6fef4974a31bc68b58e1e) and I've verified that the Danger results _do_ have something in their `markdowns` field:

```
results.(markdowns, warns)  [] [ { message: 'It looks like code was changed without adding anything to the Changelog. If this is a trivial PR that doesn\'t need a changelog, add #trivial to the PR title or body.' } ]
```

So it's a mystery why Danger-JS doesn't think there are any results.

**Comment by freak4pc** [comment]
Sounds like some token thing 🤔 very strange

**Comment by ashfurrow** [comment]
Okay so I figured it out, it has to do with how we handle the async code. Because of how the Dangerfile gets evaluated, async code needs to be wrapped in a call to `schedule`, which the code in `pr.ts` should do with `wrap`. Something isn't working because [when we call `schedule` directly](https://github.com/RxSwiftCommunity/peril/commit/96423503834c04912328856576dbd3b80fc0e471) everything works. Should have this fixed up shortly.

**Comment by orta** [comment]
Yep - details on async is here: http://danger.systems/js/guides/peril.html#dangerfile-implications

**Comment by ashfurrow** [comment]
Okay so I couldn't figure out the root cause but I realized that I was making this more difficult than it had to be. I copied `wrap` from [here](https://github.com/artsy/artsy-danger/blob/f019ee1a3abffabad65014afabe07cb9a12274e7/org/all-prs.ts#L5-L15), but it wasn't working. Debugging is kind of a nightmare because it's all JS type stuff (which I'm not good at) and the code itself is specifically designed to work differently when testing and when in production, and running locally is also difficult.

But we need `wrap` so we can unit test our rules. 

So. I took out the thing that makes `_run` and `_test` complicated: the ability to specify either a closure or a promise. It just takes whatever it gets and treats it like a promise. I don't think this is a huge concession, since most of our rules will likely be async anyway, but it leaves me perplexed why [artsy-peril](https://github.com/artsy/artsy-danger) does work with identical code?

**Comment by orta** [comment]
I hit the same problem: https://github.com/danger/peril-settings/issues/1

**Comment by ashfurrow** [comment]
Interesting! Okay, let me know what I can do to help debugging. In the mean time, we've now got a production-tested working Peril server for RxSwiftCommunity 🎉 Gonna go protect that master branch now... I'll close this PR and enable the Peril app org-wide.

**Pull request closed without merging**
