### PR TITLE
RxSwift 4.0.0 target

### PR DESCRIPTION
**Pull request by bobgodwinx**
- [x] Updated cartfile to target the new `RxSwift 4.0.0`

### CODE REVIEW

**Comment by bobgodwinx** [comment]
@fpillet @ashfurrow do think we should bump it version 3.4.0  ?

**Comment by freak4pc** [comment]
@bobgodwinx I think 4. It's a major, not a minor.

**Comment by freak4pc** [comment]
@bobgodwinx @fpillet Another point in question here. Many (most) apps didn't migrate to Swift 4 yet. Are we sure we don't want to keep Swift 4 on a branch for now? This 4.0.0 limit mean users who have the latest 3.x can't install Action.

**Comment by fpillet** [comment]
@freak4pc What I do is point to the version to use in the Readme, according to your requirements. RxSwiftExt now has 3 different options, depending on whether you need Swift 4, Swift 3 or Swift 2.x.

**Comment by freak4pc** [comment]
@fpillet Gotta. Cool that's fair :)

**Comment by bobgodwinx** [comment]
@freak4pc This is why we have versioning. Cocoapod should be able to do that based on git tags. for old version. If you specify `3.3.1` but what I was saying is that the current master branch is still pointing to `s.version      = "3.3.0-alpha.1"`

**Comment by bobgodwinx** [comment]
@freak4pc @fpillet  am merging this since it passes all tests and opened up an issues on better versioning #115 main while users can point to master with `RxSwift 4.0.0`

**Comment by ashfurrow** [comment]
Cool – let me know if/when we should ship a new version to CocoaPods. In the meantime, a PR adding a note about Swift 4 support to the Readme would be 💯

**Comment by bobgodwinx** [comment]
@ashfurrow  sounds like a plan hopefully I could get that done for tomorrow. If you can you just drop a comment on #115 just to know what suites bests.

**Pull request merged**
