### PR TITLE
Added executionObservables to provide a mechanism for observing work

### PR DESCRIPTION
**Pull request by justinswart**
Take a look at this approach, changing `Action<Void, Void>` to `Action<Void, AnyObject?>` seems to still maintain compatibility with UIButton's rx_action, however I'm still fairly new to RxSwift and Swift itself so I may not have the complete picture.

I've tested this and it allows me to use a pattern very similar to what I had been using in RAC where RACCommand had executionSignals.

If it's not quite right perhaps it'll be a nudge in the right direction :blush:

### CODE REVIEW

**Comment by fpillet** [comment]
I like the idea, this is something that exists's in RAC's `RACCommand` and can sometimes be very useful.

This said:
- you may want to push `buffer` (the `ReplaySubject`) instead of `work` so that subscribers can get a replay of the emitted elements if things go really fast
- would you mind adding some tests so the Demo project, too?

Thanks!

**Comment by justinswart** [comment]
Cool, I see some tests failed, let me take a stab at fixing that, and I'll use `buffer` instead of `work` as you suggest.  It compiled in my own project, perhaps typealias'ing `CocoaAction` as `Action<Void, AnyObject?>` won't work?

**Comment by fpillet** [comment]
Typealias works fine, I use it all the time. But CocoaAction is already typealiased to `Action<Void,Void>`

**Comment by justinswart** [comment]
Apologies, I've been travelling and forgot to get back to this.  I added one test, I'm quite new to unit testing so perhaps I'll chat to you on the Slack channel about how to do this better.

I also realise now why the typealias wouldn't work and that CocoaAction is used for compatibility with rx_action.

I don't really see a way around this unless CocoaAction on rx_action is changed to be more generic than <Void, Void>?

I'd really like to get this pattern working because it would help me to have something similar to RACCommand, perhaps you can give me some advice? 😊

**Comment by ashfurrow** [comment]
Looks good once CI is 🍏

**Comment by ashfurrow** [comment]
Hmm, same CI failure as last time:

```
Command failed due to signal: Segmentation fault: 11
```

Can you re-run the tests locally and see if that happens? Might be the `expect(string) == TestElement` being inferred as a return value.

**Comment by justinswart** [comment]
Will do!

**Comment by ashfurrow** [comment]
CI config has been updated on master, can you pull the latest changes and push to your branch? No rush!

**Comment by ashfurrow** [comment]
Thanks a lot for contributing! I've invited you to join the RxSwiftCommunity GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/RxSwiftCommunity/contributors) and feel free to reach out with any questions.

**Pull request merged**
