### PR TITLE
Swift4.0

### PR DESCRIPTION
**Pull request by fpillet**
A few code tweaks, along with project files for Swift 4 / RxSwift 4 compatibility

### CODE REVIEW

**Comment by fpillet** [comment]
Also somewhat relates to #105

**Comment by fpillet** [comment]
I looked into the Travis log. iOS tests are passing just fine, then Travis builds for macOS, watchOS and tvOS -- no problem there too. Then it tries building with SPM (`swift build`) which fails. I don't know enough about SPM to fix the SPM file, which may be just what's needed (you need to point to the `4.0.0-alpha.1` branch of RxSwift but I don't know how to do this)

**Comment by ashfurrow** [comment]
Cool cool, I'll take a look 👍

**Comment by fpillet** [comment]
@ashfurrow Actually found the description I needed hidden in the docs! Fix on its way

**Comment by ashfurrow** [comment]
This is great work – thanks!

**Pull request merged**
