### PR TITLE
Release version `3.4.0`

### PR DESCRIPTION
**Pull request by bobgodwinx**
- [x] Added change log description for release
- [x] Updated `Action.podspec` version number to match release version from `3.3.0-alpha.1` to `3.4.0` as discussed in issue #115

### CODE REVIEW

**Comment by ashfurrow** [comment]
Pulled and tested locally, everything looks 👍 Thanks again for your contributions!

**Comment by bobgodwinx** [comment]
Perfect should I create the release on with `3.4.0` tag now ?

**Comment by ashfurrow** [comment]
Oh! I've created the tag here: https://github.com/RxSwiftCommunity/Action/releases/tag/3.4.0 But if you could create a GitHub Release, that would be great (GitHub releases are needed for Carthage compatibility).

**Comment by bobgodwinx** [comment]
Done you can now do the CocoaPods trunk. 🎉

**Pull request merged**
