### PR TITLE
Carthage patch

### PR DESCRIPTION
**Pull request by bobgodwinx**
- [x] Patch for `dyld: Symbol not found` when `Action` is built with carthage
- [x] Fix for issue #112

### CODE REVIEW

**Comment by beeth0ven** [comment]
I'm sorry! I've clicked the reviewers which made unexpected review requests.

**Comment by bobgodwinx** [comment]
I am still workin on it.. in order to have a well tested and functional build for carthage.

**Comment by ashfurrow** [comment]
Thanks for all your help!

**Comment by bobgodwinx** [comment]
@ashfurrow This seems to have fixed the problem. I tested it with last commit and it works perfectly with `Carthage`. Can we release a patch tomorrow `3.4.1` Just let me know if you are fine with it.

**Comment by ashfurrow** [comment]
Sounds good 👍

**Pull request merged**
