### PR TITLE
Fix build failure on New Build System (default on Xcode 10)

### PR DESCRIPTION
**Pull request by gin0606**
same reason as https://github.com/RxSwiftCommunity/RxDataSources/issues/237

### CODE REVIEW

**Comment by gin0606** [comment]
@ashfurrow 
I Update changelog.
thx

**Comment by bobgodwinx** [comment]
@gin0606 + @ashfurrow I guess this is already done in [PR 153](https://github.com/RxSwiftCommunity/Action/pull/153/commits/b525f292eacbb35ecd9f5d949a56d2e5933b2f49)

**Comment by mAu888** [comment]
@bobgodwinx No I think this is still required. The other one was just updating to Swift 4.2. In our project we have RxSwift as a dependency as well as Action obviously. And using 3.7 (that includes the upgrade to Swift 4.2) I'm still unable to build our project. As I understand, this seems to lead to the problem described in RxSwiftCommunity/RxDataSources#237 that the new build system is trying to build Rx twice (one time from our `Cartfile` and the the one referred to from the `Action.xcworkspace`).

**Comment by ashfurrow** [comment]
I have released this as 3.8.0 but I think Carthage sometimes gets confused between git tags and GitHub releases. @bobgodwinx would you be free to draft up a GitHub release?

**Comment by mAu888** [comment]
@ashfurrow @bobgodwinx Actually I can also take care of that. It's only about writing a summary of changes, right? I don't see prebuilt binaries attached on previous releases.

**Comment by ashfurrow** [comment]
Correct, thanks!

**Comment by mAu888** [comment]
✅ done.

**Pull request merged**
