### PR TITLE
Fix #133

### LINKED ISSUE #133: Carthage build Error
Using latest Carthage version: 0.27.0

Create a brand new project and then integrate Action into the project.

Run `carthage update --platform ios`

````
*** Fetching Action
*** Fetching RxSwift
*** Checking out Action at "3.5.1"
*** Downloading RxSwift.framework binary at "Spread"
*** xcodebuild output can be found in /var/folders/jk/cd0fk3hx45jblh4c88jm_4000000gn/T/carthage-xcodebuild.Gpa7QS.log
*** Building scheme "Action-macOS" in Action.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/Wongzigii/CatchBarbie/Carthage/Checkouts/Action/Action.xcworkspace -scheme Action-macOS -configuration Release -derivedDataPath /Users/Wongzigii/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/Action/3.5.1 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/jk/cd0fk3hx45jblh4c88jm_4000000gn/T/Action SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/Wongzigii/QUQQI/CatchBarbie/Carthage/Checkouts/Action)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/jk/cd0fk3hx45jblh4c88jm_4000000gn/T/carthage-xcodebuild.Gpa7QS.log
````

### PR DESCRIPTION
**Pull request by wongzigii**
Add `FRAMEWORK_SEARCH_PATHS` flag to project config.

This should fix #133 

**How to test:**

modify your Cartfile from 

    github "RxSwiftCommunity/Action"

to 

    github "wongzigii/Action" "master"

And run `carthage update` , you are good to go now. 😄

### CODE REVIEW

**Comment by ashfurrow** [comment]
Thanks a lot for contributing! I've invited you to join the RxSwiftCommunity GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/RxSwiftCommunity/contributors) and feel free to reach out with any questions.

**Comment by wongzigii** [comment]
@ashfurrow Yes, this fix need a version bump, unfortunately.

**Comment by ashfurrow** [comment]
Awesome, that should be ready to use as 3.5.2. I've skipped pushing to CocoaPods trunk, since it's a Carthage-only fix. Thanks again!

**Comment by wongzigii** [comment]
Confirmed this work now.
````
*** Fetching Action
*** Fetching RxSwift
*** Checking out Action at "3.5.2"
*** Downloading RxSwift.framework binary at "Spread"
*** xcodebuild output can be found in /var/folders/jk/cd0fk3hx45jblh4c88jm_4000000gn/T/carthage-xcodebuild.nL1y9Y.log
*** Building scheme "Action-watchOS" in Action.xcworkspace
*** Building scheme "Action" in Action.xcworkspace
*** Building scheme "Action-tvOS" in Action.xcworkspace
*** Building scheme "Action-macOS" in Action.xcworkspace
````

**Pull request merged**
