### PR TITLE
Migrate CI from CircleCI to GitHub Actions

### PR DESCRIPTION
**Pull request by Econa77**

### CODE REVIEW

**Comment by Econa77** [comment]
The execution result of GitHub Action is as follows.
https://github.com/Econa77/Action/actions

**Review by ashfurrow — APPROVED** [review]
This looks so cool! Thank you!

**Comment by ashfurrow** [comment]
I've just told Circle CI to stop processing builds from the repo 👍

**Comment by ashfurrow** [comment]
It worked! https://github.com/RxSwiftCommunity/Action/actions/runs/748412738

**Pull request merged**
