### PR TITLE
Use RxSwift 2.1

### PR DESCRIPTION
**Pull request by carlosypunto**

### CODE REVIEW

**Comment by ashfurrow** [comment]
Super, thanks!

**Comment by ashfurrow** [comment]
I'll get a version deployed shortly.

**Comment by ashfurrow** [comment]
Coooooool should be good to go :+1: https://raw.githubusercontent.com/CocoaPods/Specs/cf5088fb64563488b0fbf3a05520489ba0217553/Specs/Action/1.2.0/Action.podspec.json

**Comment by carlosypunto** [comment]
Thanks to you Ash 👍

**Comment by ashfurrow** [comment]
🙇

**Pull request merged**
