### PR TITLE
fixed observable's disposing

### PR DESCRIPTION
**Pull request by chaserCN**
When button is deallocated, observable is not disposed.

So for example, if an application downloads some data from the internet and the user decides to cancel, download wont be stopped after uiviewcontroller is dismissed.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Code looks good, thanks for adding tests, too. Looks like the new test is failing, could you take a look when you have a moment? Happy to screenhero to tackle it together. A changelog entry would be great too, thanks again!

**Comment by zipme** [comment]
Is there way you can explicitly cancel an action?

**Comment by ashfurrow** [comment]
If the action is deallocated, it should dispose of its subscriptions. Once external objects have also dispose of their subscriptions, the action's observable (the one you create) should be disposed of. You can put cancellation code in the disposable you create with the observable.

**Comment by chaserCN** [comment]
The problem is that I use RxSwift 2.5 and travis has tested with RxSwift 2.1
Updating Podfile.lock does not help, travis cannot compile 2.5, seems like travis uses an outdated version of the compiler.

So as far as I see it now the problem is not in Action, but rather in RxSwift.

**Comment by ashfurrow** [comment]
Ah, we'll need to change the `.travis.yml` file's `osx_image` value from `xcode7.1` to `xcode7.3`. @chaserCN Can you add that to the PR?

**Comment by chaserCN** [comment]
Looks like it's ok now. 

I didn't add a Changelog entry though. I guess it would be better if a native speaker would do that, i'm not so confident in my English :)

**Comment by ashfurrow** [comment]
Fab! I can take care of that, thanks again!

**Comment by ashfurrow** [comment]
Thanks a lot for contributing! I've invited you to join the RxSwiftCommunity GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/RxSwiftCommunity/contributors) and feel free to reach out with any questions.

**Pull request merged**
