### PR TITLE
Resolve deprecations related to `bindTo` and update Action's API to match

### LINKED ISSUE #86: Deprecation warnings when using Rx >= 3.4.0
This is probably a quick fix, but I'm not certain how we'd want to version it, nor am I terribly familiar with Carthage. tl;dr `bindTo()` -> `bind(to:)`

### PR DESCRIPTION
**Pull request by tomburns**
Resolves #86 

I'd appreciate a close eye here as I haven't touched a) this repo or 2) Carthage in a little while 🙇

### CODE REVIEW

**Comment by freak4pc** [comment]
Uhm for some reason Travis is checking out RxSwift 3.3.1 
`HEAD is now at 068b4de Release 3.3.1`

**Comment by tomburns** [comment]
Yeah, I'm assuming I missed something, but nothing is jumping out. I'll keep looking...

**Comment by tomburns** [comment]
I think I may have forgotten to push the submodule changes; restarting the build to see if that sets it straight.

**Comment by tomburns** [comment]
Submodules look good on my branch, but I'm probably missing something silly: https://github.com/tomburns/Action/tree/deprecations/Carthage/Checkouts

I'll check back in on this in a bit if anyone has a sense of what's up.

**Comment by tomburns** [comment]
SPM Strikes Again! Should be all set now 👍

**Comment by freak4pc** [comment]
Nice! LGTM!

**Comment by ashfurrow** [comment]
Thanks a lot for contributing! I've invited you to join the RxSwiftCommunity GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/RxSwiftCommunity/contributors) and feel free to reach out with any questions.

**Pull request merged**
